[project]
name = "reaction-wheel-firmware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "control>=0.10.2",
    "matplotlib>=3.10.7",
    "pyperclip>=1.11.0",
    "scipy>=1.15.3",
]
